#!/bin/bash

confcopy() {
	for file in "${@}"; do
		[[ -f "$HOME/$file" ]] && [[ ! -d "$HOME/$file" ]] && [[ ! -L "$HOME/$file" ]] && rm "$HOME/$file"
		[[ -d "$HOME/$file" ]] && [[ ! -L "$HOME/$file" ]] && rm -rf "${HOME:?"notreal"}/$file"
		[[ ! -L "$HOME/$file" ]] && ln -s "$(pwd)/configs/$file" "$HOME/$file"
	done
}

sudo apt install -y zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then 
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	chsh -s "$(which zsh)"
fi
confcopy .vimrc .zshrc .shellinit .bashrc .oh-my-zsh/custom/themes/agnoster_updated.zsh-theme
